import {DsfrHead} from '@codegouvfr/react-dsfr/next-appdir/DsfrHead'
import {DsfrProvider} from '@codegouvfr/react-dsfr/next-appdir/DsfrProvider'
import {getHtmlAttributes} from '@codegouvfr/react-dsfr/next-appdir/getHtmlAttributes'
import Link from 'next/link'

import {defaultColorScheme} from './default-color-scheme.ts'
import {StartDsfr} from './start-dsfr.tsx'

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({children}) => {
  const lang = 'fr'
  return (
    <html {...getHtmlAttributes({defaultColorScheme, lang})} >
      <head>
        <StartDsfr />
        <DsfrHead Link={Link} />
      </head>
      <body>
        <DsfrProvider lang={lang}>
          {children}
        </DsfrProvider>
      </body>
    </html>
  )
}

export default RootLayout
